version: '3.1'
services:
  stats-server:
    build: ./statistic/statistic-server
    image: statistic-server-image
    container_name: statistic-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistic
      - POSTGRES_USER=akhra
      - POSTGRES_PASSWORD=aad

  stats-db:
    image: postgres:14-alpine
    container_name: statistic-data-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statistic
      - POSTGRES_USER=akhra
      - POSTGRES_PASSWORD=aad

  ewm-service:
    build: ./ewm
    image: ewm-main-server-image
    container_name: ewm-main-server-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5433/ewm
      - POSTGRES_USER=akhra
      - POSTGRES_PASSWORD=aad
      - STATISTICS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-main-data-container
    ports:
      - "6542:5433"
    command: -p 5433
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=akhra
      - POSTGRES_PASSWORD=aad
