version: '3.1'
services:
  stats-server:
    build: ./statistic/statistic-server
    image: statistic-server-image
    container_name: statistic-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm
      - POSTGRES_USER=akhra
      - POSTGRES_PASSWORD=aad

  stats-db:
    image: postgres:14-alpine
    container_name: statistic-data-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=akhra
      - POSTGRES_PASSWORD=aad

#  ewm-service:
#    ports:
#      - "8080:8080"

#  ewm-db:
#    image: postgres:14-alpine
